---
# tasks file for .

- apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - make

- get_url:
    url: "{{ go_install_url }}"
    dest: "{{ go_install_tmpfile }}"
    sha256sum: "{{ go_install_sha256 }}"

- unarchive:
    src: "{{ go_install_tmpfile }}"
    dest: /usr/local
    remote_src: yes

- lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export PATH=$PATH:/usr/local/go/bin:{{ ansible_user_dir }}/.go/bin"

- file:
    path: /usr/local/go/bin/go
    mode: 0755

- file:
    path: "{{ go_path }}/src"
    state: directory

- lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export GOPATH={{ go_path }}"

- command: "go get {{ item }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    GOPATH: "{{ go_path }}"
  with_items:
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/guru
    - github.com/nsf/gocode
    - golang.org/x/tools/cmd/gorename
    - github.com/stretchr/testify/assert
    - github.com/govend/govend
  when: go_mode == "dev"
